#!/bin/sh
# This file contains aliases used in terminal session

# Alises
alias rm="rm -ri" # Ask before deleting files recursively
alias ls="ls -Al --color=auto" # List all files including hidden ones
alias grep="grep --color=auto" # Grep
alias clean-cache="rm -rf $XDG_CACHE_HOME/*" # Clean home directory cache
alias cp="cp -r" # Copy files
alias ..="cd .." # Go up 
alias desktop="desktop-file-validate" # Validating .desktop files
alias patch-del="patch -R" # Reversing patches
alias vim="nvim" # Assume Neovim as Vim
alias commit="git commit" # Commiting Git changes
alias p="sudo pacman" # Package management
alias push="git push" # Push Git commits to upstream repository
alias pull="git pull" # Sync local Git repository with upstream
alias :x="exit" # Vim-like exit :P
