#!/bin/sh

# This file stores environment variables 
## GENERIC CONFIGURATION ##
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/bin:$HOME/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export EDITOR="nvim"
export KEYBIND="$XDG_CONFIG_HOME/sxhkd/sxhkdrc-common" # WM-independent keybindings
export AUTOSTART="$XDG_CONFIG_HOME/autostart-cmds/autostart.sh" # WM-independent autostart
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/shell/starship.toml" # Starship configuration

## DMENU SCRIPTS ##
export STARTPROMPT="startprompt"
export SETTINGS_MGR="set-mgr"
export POWER_MGR="power"

## UTILITY SCRIPTS ##
export LOCKER="locker"
export LOCK="lock" 
export SCREENSHOOTER="screenshot"

## DEFAULT APPS (For preffered apps menu) ##
export GUI_FILE_MANAGER="spacefm"
export GUI_EDITOR="nvim-qt"
export TERMINAL="alacritty"
export BROWSER="brave"
export EMAIL_CLIENT="geary"
export OFFICE_SUITE="LibreOffice-7.0.3-x86_64.AppImage"
export MEDIA_PLAYER="mpv"
export MUSIC_PLAYER="deadbeef"

## DMENU SETTINGS MANAGER ##
export STYLE="lxappearance" # Appearance
export USER_INFO="mugshot" # Account
export LOGIN="lightdm-gtk-greeter-settings" # Login screen
export RANDR="lxrandr" # Display
export NM_EDITOR="nm-connection-editor" # Network
export INPUT="lxinput" # Input devices
export POWER="xfce4-power-manager-settings" # Power
export AUDIO="pavucontrol" # Audio
export GUI_PACK="pamac-manager" # Package manager
export PRINT="system-config-printer" # Printer
