#!/bin/sh

# This file stores environment variables 
## GENERIC CONFIGURATION ##
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.local/bin:$HOME/bin" # Paths for binaries
export XDG_CONFIG_HOME="$HOME/.config" # XDG configuration directory
export XDG_DATA_HOME="$HOME/.local/share" # XDG data directory
export XDG_CACHE_HOME="$HOME/.cache" # XDG cache directory
export EDITOR="nvim"
export VISUAL="nvim"
export KEYBIND="$XDG_CONFIG_HOME/sxhkd/sxhkdrc-common" # WM-independent keybindings
export AUTOSTART="$XDG_CONFIG_HOME/autostart-cmds/autostart.sh" # WM-independent autostart
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/shell/starship.toml" # Starship configuration
export MANPAGER="nvim -c 'set ft=man'" # Use Neovim as manpager

## DMENU SCRIPTS ##
export STARTMENU="xdg-xmenu-launch"
export QUICKMENU="quickmenu"
export SETTINGS_MGR="set-mgr"
export POWER_MGR="power"

## UTILITY SCRIPTS ##
export LOCKER="xsecurelock"
export LOCK="lock" 
export SCREENSHOOTER="screenshot"

## DEFAULT APPS (For preferred apps menu) ##
export GUI_FILE_MANAGER="spacefm"
export TERMINAL="alacritty"
export BROWSER="chromium"
export EMAIL_CLIENT="geary"
export OFFICE_SUITE="OnlyOffice-x86_64.AppImage"
export MEDIA_PLAYER="mpv"
export MUSIC_PLAYER="deadbeef"

## DMENU SETTINGS MANAGER ##
export STYLE="lxappearance" # Appearance
export USER_INFO="mugshot" # Account
export LOGIN="lightdm-gtk-greeter-settings" # Login screen
export RANDR="lxrandr" # Display
export NM_EDITOR="nm-connection-editor" # Network
export BLUETOOTH="blueman-manager" # Bluetooth 
export INPUT="lxinput" # Input devices
export POWER="xfce4-power-manager-settings" # Power
export AUDIO="pavucontrol" # Audio
export GUI_PACK="pamac-manager" # Package manager
export PRINT="system-config-printer" # Printer

## XSECURELOCK SETTINGS ##
export XSECURELOCK_PASSWORD_PROMPT="cursor"
export XSECURELOCK_FONT="JetBrains Mono:size=15"
export XSECURELOCK_SWITCH_USER_COMMAND="dm-tool switch-to-greeter"
export XSECURELOCK_COMPOSITE_OBSCURER="0"
export XSECURELOCK_SHOW_DATETIME="1"
export XSECURELOCK_SHOW_HOSTNAME="2"
export XSECURELOCK_AUTH_CURSOR_BLINK="1"
export XSECURELOCK_AUTH_SOUNDS="1"

## EOF ##
