# Print a new line at the start of the prompt
add_newline = true

# Use "==> " symbol in the prompt 
[character]                            
success_symbol = "[==> ](bold blue)"    
error_symbol = "[==> ](bold red)"    

# Make a new line for each prompt
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the golang module, hiding it from the prompt completely
[golang]
disabled = true

# Disable the python module, hiding it from the prompt completely
[python]
disabled = true

# Enable the time module
[time]
disabled = false
format = '[\[󱑎 $time\]](green) '
time_format = "%T"

