#!/bin/sh

# Config 
dir="$HOME/.dwm/scriptbar"
user=$(echo "a $(whoami)")
statusbar="$dir/status"
comps="$dir/comps"

# Components
host=$(echo "󰌢 $(hostname)")
time=$(sh $comps/clock)
kerver=$(echo "󰌽 $(uname -r)")
packs=$(sh $comps/packs)
bat=$(sh $comps/battery)

# Contents of dualbar
echo " | $host | MORE COMPONENTS | $kerver | $packs | $bat | $time | " 
