// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.browsewithcaret", true);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1608902726);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1608902246);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1608902486);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1608902366);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1608902606);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1608902846);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 102);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Jive Search\",\"Qwant\",\"MetaGer\",\"Invidious\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.31.0-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.region.update.first-seen", 1608902223);
user_pref("browser.region.update.region", "MY");
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.slowStartup.averageTime", 5363);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.lastColdStartupCheck", 1608902219);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"home-button\",\"bookmarks-menu-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"search-container\",\"downloads-button\",\"preferences-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":4}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.tipShownCount.tabToSearch", 1);
user_pref("distribution.iniFile.exists.appversion", "83.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.LibreWolf.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "83.0");
user_pref("extensions.lastPlatformVersion", "83.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"05f7b5eb-5fea-4727-b22f-d9be7142c58e\",\"screenshots@mozilla.org\":\"1846154a-ab20-4356-acc4-bb595be52512\",\"default-theme@mozilla.org\":\"4ba9ba0e-faa8-4588-9d58-aaedcc55ee9b\",\"google@search.mozilla.org\":\"b3fa558a-cbdb-4292-97f0-32497c6440ed\",\"amazondotcom@search.mozilla.org\":\"9d9a1a37-e2ac-460f-833c-8b0d61c0592d\",\"wikipedia@search.mozilla.org\":\"55dc90d2-55b2-42a0-bf41-c8042cdea02d\",\"bing@search.mozilla.org\":\"db2d41aa-dd2c-498e-9430-ce892d37a8eb\",\"ddg@search.mozilla.org\":\"8f26dcd7-f850-4d54-bdcc-a048a7919d4c\",\"ebay@search.mozilla.org\":\"e7cdf6b7-2038-4e83-a897-8f2ea479192a\",\"uBlock0@raymondhill.net\":\"70210414-fe38-494f-a1b2-a8b958e97d5a\",\"firefox-compact-dark@mozilla.org\":\"bd2d0bab-a0ee-48b3-84ad-0a50d0b6eada\"}");
user_pref("identity.sendtabpromo.url", "");
user_pref("media.gmp-manager.buildID", "20201123100747");
user_pref("media.gmp-manager.lastCheck", 1608902262);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1608904276);
user_pref("security.remote_settings.intermediates.checked", 1608904276);
user_pref("security.sandbox.content.tempDirSuffix", "92fe9133-107c-44ac-9946-8738ea3509bb");
user_pref("security.sandbox.plugin.tempDirSuffix", "4f072a2a-05da-404a-8380-adf313965fa5");
user_pref("services.settings.clock_skew_seconds", -1666);
user_pref("services.settings.last_update_seconds", 1608904276);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1608904276);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1608904276);
user_pref("services.settings.main.hijack-blocklists.last_check", 1608904276);
user_pref("services.settings.main.language-dictionaries.last_check", 1608904276);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1608904276);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1608904276);
user_pref("services.settings.main.password-recipes.last_check", 1608904276);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1608904276);
user_pref("services.settings.main.public-suffix-list.last_check", 1608904276);
user_pref("services.settings.main.search-config.last_check", 1608904276);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1608904276);
user_pref("services.settings.main.search-telemetry.last_check", 1608904276);
user_pref("services.settings.main.sites-classification.last_check", 1608904276);
user_pref("services.settings.main.top-sites.last_check", 1608904276);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1608904276);
user_pref("services.settings.security.onecrl.checked", 1608904276);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("signon.usage.hasEntry", false);
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1608902214);
user_pref("toolkit.telemetry.cachedClientID", "9aebb15d-f269-449e-98e7-b07f0a65d9c8");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
