// GNU User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.enabled", false);
user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1608707239);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1608708792);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1608706966);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1608705313);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1608707119);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1608705222);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1608707359);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 55778);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.lastDir", "/home/neo64yt/Documents");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f613fca3-7e1f-4ad4-8b4b-f0bc5abf52c7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"pinTab\",\"addSearchEngine\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200929183931");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1608707096");
user_pref("browser.startup.lastColdStartupCheck", 1608707093);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"search-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"https-everywhere-eff_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq-eff_jetpack-browser-action\",\"jid1-ktlzuoiikvffew_jetpack-browser-action\",\"https-everywhere_eff_org-browser-action\",\"tprb_addon_searxes_danwin1210_me-browser-action\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"https-everywhere-eff_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq-eff_jetpack-browser-action\",\"jid1-ktlzuoiikvffew_jetpack-browser-action\",\"https-everywhere_eff_org-browser-action\",\"tprb_addon_searxes_danwin1210_me-browser-action\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.3.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.activeThemeID", "icecat-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1608707239);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppVersion", "78.3.0");
user_pref("extensions.lastPlatformVersion", "78.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.enabled", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-KtlZuoiikVfFew@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ-eff@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.tprb.addon@searxes.danwin1210.me", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c5ef16e8-b56c-4cd9-912a-56a6f33d6331\",\"formautofill@mozilla.org\":\"b2c8ec7e-8d06-4dbc-aeab-b24252ec7212\",\"screenshots@mozilla.org\":\"dc71e305-f42f-4c36-a798-09b51b59f844\",\"webcompat-reporter@mozilla.org\":\"b48f48ba-5e14-42e4-a499-5610d21a65d1\",\"webcompat@mozilla.org\":\"8cb12c4e-bbc4-4f11-8c28-3902b61a6205\",\"default-theme@mozilla.org\":\"5b5e6481-aa7b-4ffe-be56-511b7ecba17b\",\"ddg@search.mozilla.org\":\"7ae501ea-9fd4-4885-9937-d2d7ce0adb10\",\"google@search.mozilla.org\":\"1e31ea14-32ec-4eae-a945-801575d362ad\",\"amazondotcom@search.mozilla.org\":\"eb7c8765-ac28-4255-a339-1288361969b0\",\"bing@search.mozilla.org\":\"d4715096-8bfb-4af6-931e-db29618bef31\",\"ebay@search.mozilla.org\":\"1186880f-1d83-4615-a9b2-2e4599072a5d\",\"wikipedia@search.mozilla.org\":\"37454517-106a-4f9e-a441-ab9bbd8b0bf6\",\"icecat-compact-dark@mozilla.org\":\"d9619f51-7b3a-416c-8870-3be994c54ee9\",\"jid1-KtlZuoiikVfFew@jetpack\":\"eebedf7c-4b48-4f9f-9aef-ada1a77be568\",\"rsf@0xbeef.coffee\":\"4c59858b-64a2-40a3-8553-7922d9561bbb\",\"SubmitMe@0xbeef.coffee\":\"abfb8711-179a-4251-8e5d-ea817c256bd0\",\"https-everywhere@eff.org\":\"17b41a85-dbe6-45f3-a9b2-9e753c5e32bf\",\"tprb.addon@searxes.danwin1210.me\":\"1bb30b40-bb01-4a4c-894b-3a71652bc567\",\"FreeUSPS@0xbeef.coffee\":\"e49826cb-3906-47dd-b567-e0927cf00d7f\",\"goteo@0xbeef.coffee\":\"9b8bf0fd-9306-49a1-9246-49171c85ec16\",\"DMCAreg@0xbeef.coffee\":\"d616917f-5b8a-4500-bb12-6db8956b97bf\",\"google_drive@0xbeef.coffee\":\"6086172d-2f92-41a4-a20a-4ffbc872c220\",\"SimpleSumOfUs@0xbeef.coffee\":\"2300f206-94eb-4c03-bda7-bb136a34ac1f\",\"viewtube@extension\":\"182a9a39-2843-4a9f-9fb6-cdae435c573d\",\"disable-polymer-youtube@extension\":\"41ead2bc-0d3c-48dd-b250-2a112e653150\",\"jid1-MnnxcxisBPnSXQ-eff@jetpack\":\"7be748f6-ea17-4826-acde-53f0545ab925\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-manager.buildID", "20200929183931");
user_pref("media.gmp-manager.lastCheck", 1608708455);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6449f1a7-8421-4ee0-8e5c-6f84eb6848b2");
user_pref("security.sandbox.plugin.tempDirSuffix", "ca565217-f072-4ee2-a18f-9291c52a1daf");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1608707086);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200929183931");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
