#! /bin/sh

# Config directory
export WM_CONFIG_DIR="$XDG_CONFIG_HOME/bspwm"

# Quitting bspwm
export SESSION_KILLER="$WM_CONFIG_DIR/session-killer"

# Autostart file
export WM_AUTOSTART="$WM_CONFIG_DIR/autostart.sh"

# Keybindings
export WM_KEYBIND="$WM_CONFIG_DIR/edit-keybinds"

# Autostart file
$WM_AUTOSTART &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
