#!/bin/sh

# Updates the tracked dotfiles
# For new file, please add it 
# Example: "/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.blahblah"
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.config
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.local
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.face
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.gtkrc-2.0
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.p10k.zsh
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.xinitrc
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.xprofile
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.zprofile
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/.zshrc
/usr/bin/git --git-dir=$HOME/git-src/dotfiles/ --work-tree=$HOME add $HOME/README.md

# Changes must be manually commited
