#!/bin/sh

# Scripts directory

# Defaults
lines=2
columns=2
border=3
height=35
prompt="󰐦 Session manager:"

# Command
choice=$(echo -e "󰐥 Shutdown\n󰜉 Restart\n󰍁 Lock\n󰍃 Log out" | dmenu -l $lines -g $columns -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰐥 Shutdown") poweroff ;;
  "󰜉 Restart") reboot ;;
  "󰍁 Lock") light-locker-command -l ;;
  "󰍃 Log out") sh $SESSION_KILLER ;;
esac
