#!/bin/sh

# Scripts directory

# Defaults
lines=5
border=3
height=35
prompt="󰐦 Session manager:"

# Command
choice=$(echo "󰐥 Shutdown\n󰜉 Restart\n󰍁 Lock\n󰍃 Log out" | dmenu -l $lines -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰐥 Shutdown") poweroff ;;
  "󰜉 Restart") reboot ;;
  "󰍁 Lock") $LOCKER ;;
  "󰍃 Log out") sh $SESSION_KILLER ;;
esac
