#!/bin/sh

# Settings manager

# Defaults
lines=5
columns=2
border=3
height=35
prompt="󰢻 Settings:"
edit="nvim-qt"

# Command
choice=$(echo -e "󰸌 Appearance\n󰿻 Account\n󰍁 Lock screen\n󰍂 Login screen\n󰂳 Bluetooth\n󰍹 Display\n󰲝 Network\n󰧺 Input devices\n󰐦 Power\n󰕾 Audio\n󰏗 Package manager\n󰘔 Default applications\n󰜇 Printer\n󰌧 Autostart" | dmenu -l $lines -g $columns -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰸌 Appearance") $STYLE ;;
  "󰿻 Account") $USER_INFO ;;
  "󰍁 Lock screen") $LOCK ;;
  "󰍂 Login screen") pkexec $LOGIN ;;
  "󰂳 Bluetooth") $BT ;;
  "󰍹 Display") $RANDR ;;
  "󰲝 Network") $NM ;;
  "󰧺 Input devices") $INPUT ;;
  "󰐦 Power") $POWER ;;
  "󰕾 Audio") $AUDIO ;;
  "󰏗 Package manager") $PACK ;;
  "󰘔 Default applications") $DEF_APPS ;;
  "󰜇 Printer") $PRINT ;;
  "󰌧 Autostart") $edit $AUTOSTART ;;
esac
