#!/bin/sh

# Scripts directory
dir="$HOME/.dmenu"

# Defaults
lines=10
border=3
height=35
prompt="󱍕 Select a prompt to run:"

# Scripts
appmenu="$dir/apps"
run="$dir/runner"
session="$dir/power"
settings="$dir/set"
emoji="$dir/dmenuunicode"
password="$dir/passprompt"

choice=$(echo "󰀻 Applications\n󰆍 Run\n󰐦 Session manager\n󰱨 Emojis\n󰢻 Settings\n󰷖 Passwords" | dmenu -l $lines -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰀻 Applications") sh $appmenu ;;
  "󰆍 Run") sh $run ;;
  "󰐦 Session manager") sh $session ;;
  "󰱨 Emojis") sh $emoji & ;;
  "󰢻 Settings") sh $settings ;;
  "󰷖 Passwords") sh $password ;;
esac
