#!/bin/sh

# Scripts directory
dir="$HOME/.dmenu"

# Defaults
lines=3
columns=2
border=3
height=35
prompt="󱍕 Select a prompt to run:"

# Scripts
appmenu="$dir/apps"
run="$dir/runner"
session="$dir/power"
settings="$dir/set"

choice=$(echo "󰀻 Applications\n󰆍 Run\n󰐦 Session manager\n󰱨 Emojis\n󰢻 Settings" | dmenu -l $lines -g $columns -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰀻 Applications") sh $appmenu ;;
  "󰆍 Run") sh $run ;;
  "󰐦 Session manager") sh $session ;;
  "󰱨 Emojis") $TERMINAL & ;;
  "󰢻 Settings") sh $settings ;;
esac
