#!/bin/sh

# Defaults
lines=10
border=3
height=35
prompt="󱍕 Select a prompt to run:"

# Scripts
appmenu="$DMENU_SCRIPTS/apps"
run="$DMENU_SCRIPTS/runner"
session="$DMENU_SCRIPTS/power"
settings="$DMENU_SCRIPTS/set"
emoji="$DMENU_SCRIPTS/dmenuemoji"
password="$DMENU_SCRIPTS/passprompt"
apps="$DMENU_SCRIPTS/prefapps"

choice=$(echo "󰀻 Applications\n󰩴 Preferred applications\n󰆍 Run\n󰐦 Session manager\n󰱨 Emojis\n󰢻 Settings\n󰷖 Passwords" | dmenu -l $lines -bw $border -h $height -p "$prompt" -c )

case "$choice" in
  "󰀻 Applications") sh $appmenu ;;
  "󰩴 Preferred applications") sh $apps ;;
  "󰆍 Run") sh $run ;;
  "󰐦 Session manager") sh $session ;;
  "󰱨 Emojis") sh $emoji & ;;
  "󰢻 Settings") sh $settings ;;
  "󰷖 Passwords") sh $password ;;
esac
