#!/bin/sh

# Default height to use
height=$(echo 30)

# Default count of lines to use
lines=$(echo 12)

# Default count of columns
grid=$(echo 2)

# Title of the prompt
title=$(echo "Select a prompt to use :")

# Default width of border
border=$(echo 3)

# Command to run the prompt
choice=$(echo -e "Applications\nRun Prompt\nSession Manager" | dmenu -p "$title" -h "$height" | cut -f 1)

# Names for each prompt
apps=$(echo "Applications :")
run=$(echo "Run a command :")

case "$choice" in
  "Applications") j4-dmenu-desktop --term="termite" --dmenu="dmenu -p '$apps' -l '$lines' -g '$grid' -h '$height' -bw '$border' -c"    ;;
  "Run Prompt") dmenu_run -p "$run" -l "$lines" -g "$grid" -h "$height"  -bw "$border" -c     ;;
  "Session Manager") ~/.dwm/session     ;;
esac
