#!/bin/sh

# Default height to use
height=$(echo 30)

# Default count of lines to use
lines=$(echo 2)

# Default count of columns to use
grid=$(echo 2)

# Title of the prompt
title=$(echo "dwm session manager :")


choice=$(echo -e "Log out of this session\nLock this session\nShutdown\nRestart" | dmenu -p "$title" -l "$lines" -g "$grid" -h "$height" -c | cut -f 1)

case "$choice" in
  "Log out of this session") sh $SESSION_KILLER    ;;
  "Lock this session") betterlockscreen -l dimblur    ;;
  "Shutdown") poweroff    ;;
  "Restart") reboot    ;;
esac
