// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1608903107);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 102);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Jive Search\",\"Qwant\",\"MetaGer\",\"Invidious\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.region.update.first-seen", 1608903105);
user_pref("browser.region.update.region", "MY");
user_pref("browser.slowStartup.averageTime", 5453);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.lastColdStartupCheck", 1608903099);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "83.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.LibreWolf.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "83.0");
user_pref("extensions.lastPlatformVersion", "83.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9d3bd089-fc48-4bc9-bc31-2b6de2ef9cef\",\"screenshots@mozilla.org\":\"cc653b8b-be89-4070-aa65-f5b513650310\",\"default-theme@mozilla.org\":\"a16b2297-8650-4ff2-bc06-b2e34832ada6\",\"google@search.mozilla.org\":\"a26814b5-8efc-4d2d-923d-56875bd8f553\",\"amazondotcom@search.mozilla.org\":\"219b87e5-e48c-41e8-b686-acdbc59a9f3a\",\"wikipedia@search.mozilla.org\":\"47cf42ae-7fdc-4b9e-8182-5e9664059c3b\",\"bing@search.mozilla.org\":\"6ca4787d-f1c1-4a9e-8c89-104861753bf4\",\"ddg@search.mozilla.org\":\"9ae86053-1d75-45b9-a9fd-a5d27c4a7402\",\"ebay@search.mozilla.org\":\"aae3da40-5b91-4ac6-a71e-d590d4d46f1d\"}");
user_pref("identity.sendtabpromo.url", "");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ae9b870c-aeeb-438b-84d4-f96908f7bc22");
user_pref("security.sandbox.plugin.tempDirSuffix", "4ebcd137-cb2e-4f6e-b8a7-e126b4238181");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("signon.usage.hasEntry", false);
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("toolkit.startup.last_success", 1608903093);
user_pref("toolkit.telemetry.cachedClientID", "97438870-0a34-45bc-b8f9-44e88d57ca96");
